= GSAnnotator-Java

image:https://img.shields.io/badge/vert.x-4.4.6-white.svg[link="https://vertx.io"]

== Supported annotation databases:
* dbNSFP v4.3a
* gnomAD v4
* SpliceAI v1.3
* ClinVar
* GERP
* dbSNP

== Setup: Building and Running [Linux/MacOS]

Clone the master branch and package the application as a JAR file:
[source,bash]
----
git clone git@github.com:ForomePlatform/gs-annotator.git
cd gs-annotator
./mvnw clean package
----

The JAR file will be generated inside the *target* directory as *annotator-1.0.0.jar*.

- On the first run the application creates a data folder in the user's home directory with the name *GSAnnotator* by default if not specified otherwise.
- The service is running on port *8000* by default if not specified otherwise.

NOTE: These properties can be adjusted using a *config.json* file.

*config.json* example:
[source,json]
----
{
	"dataDirectoryPath": "/home/user/ExampleAnnotator",
    "serverPort": 3000,
    "aStorageServerUrl": "http://localhost:8080/"
}
----

To start the application run:
[source,bash]
----
cd target
java -jar annotator-1.0.0.jar
----

NOTE: Annotator logs are being written in <dataDirectoryPath>/output_<currentTimeMillis>.log file.

For detailed API specification access the Swagger UI via: http://localhost:8000/api.

== Annotation

To perform annotation of variants in your specified VCF:

NOTE: To use the annotation service AStorage service should be running on the configured AStorage server URL.

[source,bash]
----
curl -X POST -OJ 'http://localhost:8000/annotation/anfisa' -H 'accept: application/jsonl' -H 'Content-Type: multipart/form-data' -F 'cfgFile=@<path to .cfg file>' -F 'famFile=@<path to .fam file>' -F 'vcfFile=@<path to .vcf file>'
----

API reference: link:http://localhost:8000/api/#/Annotation/post_annotation_anfisa[Anfisa Annotation].
