= GSAnnotator-Java

image:https://img.shields.io/badge/vert.x-4.4.6-white.svg[link="https://vertx.io"]

== Supported annotation databases:
* dbNSFP v4.3a
* gnomAD v4
* SpliceAI v1.3
* ClinVar
* GERP
* dbSNP

== Setup: Building and Running [Linux/MacOS]

Clone the master branch and package the application as a JAR file:
[source,bash]
----
git clone git@github.com:ForomePlatform/gs-annotator.git
cd gs-annotator
./mvnw clean package
----

The JAR file will be generated inside the *target* directory as *annotator-1.0.0.jar*.

On the first run the application creates a data folder in the user's home directory by default with the name *GSAnnotator*.

To start the application run:
[source,bash]
----
cd target
java -jar annotator-1.0.0.jar
----

The service is only running on *localhost:8000* for now.

For detailed API specification access the Swagger UI via: http://localhost:8000/swagger.

== Annotation

To perform annotation of variants in your specified VCF:

NOTE: To use the annotation service AStorage service should be running on *localhost:8080*.

[source,bash]
----
curl -X POST -OJ 'http://localhost:8000/annotation/anfisa' -H 'accept: application/jsonl' -H 'Content-Type: multipart/form-data' -F 'cfgFile=@<path to .cfg file>' -F 'famFile=@<path to .fam file>' -F 'vcfFile=@<path to .vcf file>'
----

NOTE: For now the FAM file isn't necessary and from the CFG JSON file only *"assembly": "GRCh38"* key-value pair is required.

API reference: link:http://localhost:8000/swagger/#/Annotation/post_annotation_anfisa[Swagger Anfisa Annotation].
