openapi: 3.0.0
info:
  title: GSAnnotator API
  description: API for annotating variants in your specified VCF.
  version: 1.0.0
servers:
  - url: http://localhost:8000/
    description: Local server
paths:
  /annotation/anfisa:
    post:
      tags: [
        Annotation
      ]
      summary: Annotates given VCF and returns Anfisa file
      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                cfgFile:
                  type: string
                  format: binary
                  example: path to .cfg file
                famFile:
                  type: string
                  format: binary
                  example: path to .fam file
                vcfFile:
                  type: string
                  format: binary
                  example: path to .vcf file
      responses:
        '200':
          description: Annotated Anfisa file
          content:
            application/jsonl:
              schema:
                $ref: '#/components/schemas/AnnotationResult'

  /stop:
    get:
      tags: [
        Utils
      ]
      summary: Stops the GSAnnotator service
      responses:
        '200':
          description: Success message in JSON
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/SuccessMessage'

components:
  schemas:
    SuccessMessage:
      type: object
      properties:
        success:
          type: string
          description: Success message
    AnnotationResult:
      type: string
      format: binary
      example: "JSON lines of annotated Anfisa records..."
    AnfisaRecord:
      allOf:
        - $ref: '#/components/schemas/GnomADRecord'
        - $ref: '#/components/schemas/ClinVarRecord'
    GnomADRecord:
      type: object
      properties:
        gnomad_af:
          type: integer
          example: 0
          nullable: true
        gnomad_af_exomes:
          type: string
          example: "0.00000"
          nullable: true
        gnomad_af_genomes:
          type: string
          example: "0.00000"
          nullable: true
        gnomad_popmax:
          type: string
          example: "XX"
          nullable: true
        gnomad_popmax_af:
          type: integer
          example: 0
          nullable: true
        gnomad_popmax_an:
          type: integer
          example: 0
          nullable: true
        gnomad_popmax_outbred:
          type: string
          example: "XX"
          nullable: true
        gnomad_popmax_af_outbred:
          type: integer
          example: 0
          nullable: true
        gnomad_popmax_an_outbred:
          type: integer
          example: 20
          nullable: true
        gnomad_hom:
          type: integer
          example: 0
          nullable: true
        gnomad_hem:
          type: integer
          example: 0
          nullable: true
    ClinVarRecord:
      type: object
      properties:
        clinvar_submitters:
          type: array
          items:
            type: object
            properties:
              SubmitterID:
                type: string
                example: "3"
              SubmitterName:
                type: string
                example: "OMIM"
          nullable: true
        clinvar_benign:
          type: boolean
          example: false
          nullable: true
        clinvar_significance:
          type: string
          example: "Pathogenic"
          nullable: true
        clinvar_trusted_significance:
          type: array
          items:
            type: string
            example: "\\n"
          nullable: true
        clinvar_trusted_simplified:
          type: integer
          example: 0
          nullable: true
        clinvar_stars:
          type: string
          example: "two"
          nullable: true
        number_of_clinvar_submitters:
          type: integer
          example: 2
          nullable: true
        clinvar_review_status:
          type: string
          example: "criteria provided, multiple submitters, no conflicts"
          nullable: true
        clinvar_criteria_provided:
          type: boolean
          example: true
          nullable: true
        clinvar_conflicts:
          type: boolean
          example: false
          nullable: true
        clinvar_acmg_guidelines:
          type: string
          example: "-"
          nullable: true